# Generated by Django 5.1.1 on 2026-08-22 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_review_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=70, verbose_name='Код подтверждения'),
        ),
    ]
